disabled_rules:
   - trailing_whitespace
opt_in_rules:
   - empty_count
   - empty_string
excluded:
   - Carthage
   - Pods
   - SwiftLint/Common/3rdPartyLib
   - Sources/ExcludedFolder
   - Sources/ExcludedFile.swift
   - Sources/*/ExcludedFile.swift # exclude files with a wildcard
analyzer_rules: # rules run by `swiftlint analyze`
  - explicit_self
line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    warning: 300
    error: 500
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 300
    error: 400
file_length:
    warning: 500
    error: 1200
    ignore_comment_only_lines: true
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names
reporter: "xcode"
